package com.wiva.android.hardware.controller

/** Исходящие команды (TX),ts]. */
@Suppress("EnumEntryName", "SpellCheckingInspection")
enum class RequestCommand(val code: Int) {
    Undefined(0x00),
    AX(0x09),
    DX(0x10),
    RX(0x11),
    RFIDDevice(0x22),
    GiveCup(0x46),
    CupCheck(0x47),
    SendSumToPaymentTerminal(0x48),
    ChooseSnackProduct(0x49),
    ChooseDrink(0x50),
    SnackTemperatureControll(0x51),
    ServiceCommand(0x52),
    SetBoilerCoolerModuleState(0x54),
    StartDrinkPreparing(0x55),
    SetVentilationState(0x61),
    ReadDrinkPrices(0x66),
    ReadDrinkActiveStatus(0x67),
    SetCirclePumpStatus(0x68),
    ReadControllerErrors(0x69),
    FirstLaunch_WatterSystemFilling(0x70),
    ReadPincode(0x87),
    ReadSerialNum(0x89),
    ReadDeviceMode(0x94),
    RestartController(0x95),
    PumpingWater(0x96),
    ReadFirmwareVersion(0x97),
    PaymentSystemsExist(0x98),
    PaymentType(0x99),
    WriteFirstStepCount(0x9c),
    WriteSecondStepCount(0x9d),
    WriteCoinOrCash(0x9e),
    ReadCoinOrCash(0x9f),
    ReadStepCount(0xa1),
    WastesModule(0xa4),
    WriteCurrencyNumber(0xa5),
    ReadCurrencyNumber(0xa6),
    UserManagerSetWindow(0xa7),
    ReadRFIDVersion(0xaa),
    WriteRFIDVersion(0xab),
    GiveChange(0xac),
    ReadMDBLevel(0xad),
    WriteMDBLevel(0xae),
    WriteInvertCupSensor(0xb0),
    ReadInvertCupSensor(0xb1),
    ChargeOffTheCredit(0xb2),
    WriteWashAfterEveryShake(0xb3),
    ReadWashAfterEveryShake(0xb4),
    SnackOpenDoor(0xb5),
    WriteMDBLogs(0xb6),
    ReadMDBLogs(0xb7),
    ResetWaterCounter(0xb8),
    ReadWaterCounter(0xb9),
    FunctionalTest(0xba),
    WriteWaterPumpModel(0xbb),
    ReadWaterPumpModel(0xbc),
    SetupBoilerStatus(0xbd),
    PumpPeristalticPump(0xbe),
    WriteCupSensorStatus(0xc0),
    ReadCupSensorStatus(0xc1),
    AutoWash(0xc6),
    WriteHandModuleStatus(0xc7),
    ReadHandModuleStatus(0xc8),
    SendCashSaleInfo(0xcc),
    OpenElectricLock(0xce),
    WaterPourByTouch(0xd0),
    ReadFlowTemperature(0xd1),
    SetFlowRgb(0xd2),
    ReadFlowBucketStatus(0xd3),
    ;

    companion object {
        private val byCode: Map<Int, RequestCommand> = entries.associateBy { it.code }

        fun fromCode(code: Int): RequestCommand? = byCode[code]
    }
}
