package com.viwa.android.ui.screens.service.devices

/** User-visible strings for serial/USB devices block (kiosk defaults or hybrid locales). */
data class DevicesBlockUiLabels(
    val title: String,
    val description: String,
    val noDevicesFound: String,
    val findScanner: String,
    val findController: String,
    val findPayment: String,
    val refreshList: String,
    val discoveryInProgress: String,
    val scannerNotAssignedTitle: String,
    val scannerNotAssignedDetails: String,
    val scannerConnectedTitle: String,
    val scannerConnectedPort: String,
    val scannerErrorTitle: String,
    val scannerErrorDetails: String,
    val paymentNotAssignedTitle: String,
    val paymentNotAssignedDetails: String,
    val paymentReadyTitle: String,
    val paymentReadyPort: String,
    val paymentErrorTitle: String,
    val paymentErrorDetails: String,
    val controllerMockTitle: String,
    val controllerMockTitleWithSection: String,
    val controllerMockDetails: String,
    val controllerNotAssignedTitle: String,
    val controllerNotAssignedDetailsPrimary: String,
    val controllerNotAssignedDetailsLegacy: String,
    val controllerAssignedTitle: String,
    val controllerAssignedPort: String,
    val controllerErrorTitle: String,
    val controllerErrorDetails: String,
    val mockControllerTitle: String,
    val mockControllerDescription: String,
    val serialDriverFound: String,
    val serialDriverNotFound: String,
    val findScannerDialogTitle: String,
    val findScannerNoDevices: String,
    val findPaymentDialogTitle: String,
    val findPaymentNoDevices: String,
    val findStartSearch: String,
    val findStopSearch: String,
    val findCancel: String,
) {
    companion object {
        /** Legacy kiosk Russian strings when [DevicesBlockContent] is used without hybrid labels. */
        val KioskDefaults =
            DevicesBlockUiLabels(
                title = "Serial-порты и USB",
                description =
                    "Показываем /dev/tty* узлы платы и USB-serial. " +
                        "Роль можно назначить портам с найденным драйвером.",
                noDevicesFound = "Serial-порты и USB-устройства не обнаружены",
                findScanner = "Найти сканер",
                findController = "Автопоиск контроллера",
                findPayment = "Найти платёжник",
                refreshList = "Обновить список",
                discoveryInProgress = "Поиск…",
                scannerNotAssignedTitle = "Сканер не назначен",
                scannerNotAssignedDetails =
                    "Нажмите «Найти сканер» или назначьте роль SCANNER найденному USB serial устройству.",
                scannerConnectedTitle = "Сканер подключён",
                scannerConnectedPort = "Порт: %1\$s",
                scannerErrorTitle = "Сканер недоступен",
                scannerErrorDetails = "%1\$s: %2\$s",
                paymentNotAssignedTitle = "Платёжник не назначен",
                paymentNotAssignedDetails =
                    "Нажмите «Найти платёжник» или назначьте роль PAYMENT serial-порту (MDB / USB).",
                paymentReadyTitle = "Платёжник готов",
                paymentReadyPort = "Порт: %1\$s",
                paymentErrorTitle = "Платёжник недоступен",
                paymentErrorDetails = "%1\$s: %2\$s",
                controllerMockTitle = "Контроллер: MOCK",
                controllerMockTitleWithSection = "%1\$s: MOCK",
                controllerMockDetails = "UART отключён — команды идут в программный эмулятор.",
                controllerNotAssignedTitle = "Контроллер не назначен",
                controllerNotAssignedDetailsPrimary =
                    "Нажмите «Автопоиск контроллера» или назначьте роль PRIMARY_CONTROLLER порту.",
                controllerNotAssignedDetailsLegacy =
                    "Нажмите «Автопоиск контроллера» или назначьте роль CONTROLLER порту.",
                controllerAssignedTitle = "Контроллер назначен",
                controllerAssignedPort = "Порт: %1\$s",
                controllerErrorTitle = "Контроллер недоступен",
                controllerErrorDetails = "%1\$s: %2\$s",
                mockControllerTitle = "Mock-контроллер",
                mockControllerDescription = "Для отладки UI без UART. Отключите перед автопоиском на плате.",
                serialDriverFound = "Serial driver: %1\$s",
                serialDriverNotFound = "Serial driver: не найден",
                findScannerDialogTitle = "Поиск сканера",
                findScannerNoDevices = "Нет USB устройств с serial-драйвером",
                findPaymentDialogTitle = "Поиск платёжника",
                findPaymentNoDevices = "Нет USB устройств AQSI (VID 0FB9 / PID 2606)",
                findStartSearch = "Начать поиск",
                findStopSearch = "Остановить",
                findCancel = "Отмена",
            )
    }
}
